### ISSUE TITLE
How to install chromium

### ISSUE THREAD

**Issue by fahadali32** [rishabhrpg/puppeteer-on-termux#1]
By this cmd i can't install chromium

**Comment by rishabhrpg** [comment]
@fahadali32 Can you paste some screenshots or error logs here.

**Comment by fahadali32** [comment]
![Uploading Screenshot_2021-06-03-15-20-19-015_com.termux.jpg…]()

**Comment by fahadali32** [comment]
$ pkg install proot-distro
Checking availability of current mirror: ok
Hit:2 https://grimler.se/game-packages-24 games InRelease
Hit:3 https://grimler.se/science-packages-24 science InRelease                                      Get:1 https://packages.termux.org/apt/termux-main stable InRelease [14.0 kB]                        Get:4 https://packages.termux.org/apt/termux-main stable/main arm Packages [243 kB]                 Fetched 257 kB in 8s (31.9 kB/s)
Reading package lists... Done
Building dependency tree... Done                  Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
proot-distro is already the newest version (1.7.0-2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
$ pkg install proot-distro
Checking availability of current mirror: ^Cok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
proot-distro is already the newest version (1.7.0-2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
$ proot-distro install alpine
[*] Installing Alpine Linux 3.13.1...
[*] Creating directory '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/alpine'...
[*] Creating directory '/data/data/com.termux/files/usr/var/lib/proot-distro/dlcache'...
[*] Downloading rootfs tarball...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:-  0     0    0     0    0     0      0      0 --:-100   645  100   645    0     0    999      0 --:--:-- --:--:-- --:--:--   998
  0     0    0     0    0     0      0      0 --:-  7 2311k    7  174k    0     0  83982      0  0:0 21 2311k   21  498k    0     0   159k      0  0:0 33 2311k   33  776k    0     0   188k      0  0:0 45 2311k   45 1040k    0     0   200k      0  0:0 57 2311k   57 1319k    0     0   213k      0  0:0 70 2311k   70 1619k    0     0   227k      0  0:0 82 2311k   82 1913k    0     0   235k      0  0:0 92 2311k   92 2143k    0     0   234k      0  0:0100 2311k  100 2311k    0     0   238k      0  0:00:09  0:00:09 --:--:--  282k

[*] Checking integrity, please wait...
[*] Extracting rootfs, please wait...
[*] Writing '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/alpine/etc/profile.d/termux-proot.sh'...
[*] Writing resolv.conf file (NS 1.1.1.1/1.0.0.1)...
[*] Writing hosts file...
[*] Registering Android-specific UIDs and GIDs...
[*] Running distro-specific configuration steps...
[*] Installation finished.

Now run 'proot-distro login alpine' to log in.

$ apk update && apk add --no-cache nmap && \
>   echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
>   echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
>   apk update && \
>   apk add --no-cache \
>   chromium
No command apk found, did you mean:
 Command ack in package ack-grep
 Command apt in package apt
 Command awk in package gawk
$ proot-distro login alpine
localhost:~# apk update && apk add --no-cache nmap
 && \
>   echo @edge http://nl.alpinelinux.org/alpine/ed
ge/community >> /etc/apk/repositories && \
>   echo @edge http://nl.alpinelinux.org/alpine/ed
ge/main >> /etc/apk/repositories && \
(4/7) Installing pcre (8.44-r0)
  2% █
>   chromium
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
v3.13.5-161-ga1fa812b9a [https://dl-cdn.alpinelinux.org/alpine/v3.13/main]
v3.13.5-159-g0fcb259c12 [https://dl-cdn.alpinelinux.org/alpine/v3.13/community]
OK: 13499 distinct packages available
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
(1/7) Installing libgcc (10.2.1_pre1-r3)
(2/7) Installing lua5.3-libs (5.3.6-r0)
(3/7) Installing libpcap (1.10.0-r0)
(5/7) Installing libssh2 (1.9.0-r1)
(6/7) Installing libstdc++ (10.2.1_pre1-r3)
(7/7) Installing nmap (7.91-r0)
Executing busybox-1.32.1-r2.trigger
OK: 17 MiB in 21 packages
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/community/armv7/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/main/armv7/APKINDEX.tar.gz
v3.13.5-161-ga1fa812b9a [https://dl-cdn.alpinelinux.org/alpine/v3.13/main]
v3.13.5-159-g0fcb259c12 [https://dl-cdn.alpinelinux.org/alpine/v3.13/community]
v20210212-8114-gc237ed0a83 [http://nl.alpinelinux.org/alpine/edge/community]
v20210212-8104-g2ffc8e8361 [http://nl.alpinelinux.org/alpine/edge/main]
OK: 27137 distinct packages available
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/community/armv7/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/main/armv7/APKINDEX.tar.gz
ERROR: unable to select packages:
  chromium (no such package):
    required by: world[chromium]
localhost:~#

**Comment by rishabhrpg** [comment]
were you able to log in to alpine?

**Comment by fahadali32** [comment]
@rishabhrpg 
Here is it
$ pkg install proot-distro
Checking availability of current mirror: ok
Hit:2 https://grimler.se/game-packages-24 games InRelease
Hit:3 https://grimler.se/science-packages-24 science InRelease                                      Get:1 https://packages.termux.org/apt/termux-main stable InRelease [14.0 kB]                        Get:4 https://packages.termux.org/apt/termux-main stable/main arm Packages [243 kB]                 Fetched 257 kB in 8s (31.9 kB/s)
Reading package lists... Done
Building dependency tree... Done                  Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
proot-distro is already the newest version (1.7.0-2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
$ pkg install proot-distro
Checking availability of current mirror: ^Cok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
proot-distro is already the newest version (1.7.0-2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
$ proot-distro install alpine
[*] Installing Alpine Linux 3.13.1...
[*] Creating directory '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/alpine'...
[*] Creating directory '/data/data/com.termux/files/usr/var/lib/proot-distro/dlcache'...
[*] Downloading rootfs tarball...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:-  0     0    0     0    0     0      0      0 --:-100   645  100   645    0     0    999      0 --:--:-- --:--:-- --:--:--   998
  0     0    0     0    0     0      0      0 --:-  7 2311k    7  174k    0     0  83982      0  0:0 21 2311k   21  498k    0     0   159k      0  0:0 33 2311k   33  776k    0     0   188k      0  0:0 45 2311k   45 1040k    0     0   200k      0  0:0 57 2311k   57 1319k    0     0   213k      0  0:0 70 2311k   70 1619k    0     0   227k      0  0:0 82 2311k   82 1913k    0     0   235k      0  0:0 92 2311k   92 2143k    0     0   234k      0  0:0100 2311k  100 2311k    0     0   238k      0  0:00:09  0:00:09 --:--:--  282k

[*] Checking integrity, please wait...
[*] Extracting rootfs, please wait...
[*] Writing '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/alpine/etc/profile.d/termux-proot.sh'...
[*] Writing resolv.conf file (NS 1.1.1.1/1.0.0.1)...
[*] Writing hosts file...
[*] Registering Android-specific UIDs and GIDs...
[*] Running distro-specific configuration steps...
[*] Installation finished.

Now run 'proot-distro login alpine' to log in.

$ apk update && apk add --no-cache nmap && \
>   echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
   echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
>   apk update && \
>   apk add --no-cache \
>   chromium
No command apk found, did you mean:
 Command ack in package ack-grep
 Command apt in package apt
 Command awk in package gawk
$ proot-distro login alpine
localhost:~# apk update && apk add --no-cache nmap
 && \
>   echo @edge http://nl.alpinelinux.org/alpine/ed
ge/community >> /etc/apk/repositories && \
>   echo @edge http://nl.alpinelinux.org/alpine/ed
ge/main >> /etc/apk/repositories && \
(4/7) Installing pcre (8.44-r0)
  2% █
>   chromium
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
v3.13.5-161-ga1fa812b9a [https://dl-cdn.alpinelinux.org/alpine/v3.13/main]
v3.13.5-159-g0fcb259c12 [https://dl-cdn.alpinelinux.org/alpine/v3.13/community]
OK: 13499 distinct packages available
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
(1/7) Installing libgcc (10.2.1_pre1-r3)
(2/7) Installing lua5.3-libs (5.3.6-r0)
(3/7) Installing libpcap (1.10.0-r0)
(5/7) Installing libssh2 (1.9.0-r1)
(6/7) Installing libstdc++ (10.2.1_pre1-r3)
(7/7) Installing nmap (7.91-r0)
Executing busybox-1.32.1-r2.trigger
OK: 17 MiB in 21 packages
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/community/armv7/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/main/armv7/APKINDEX.tar.gz
v3.13.5-161-ga1fa812b9a [https://dl-cdn.alpinelinux.org/alpine/v3.13/main]
v3.13.5-159-g0fcb259c12 [https://dl-cdn.alpinelinux.org/alpine/v3.13/community]
v20210212-8114-gc237ed0a83 [http://nl.alpinelinux.org/alpine/edge/community]
v20210212-8104-g2ffc8e8361 [http://nl.alpinelinux.org/alpine/edge/main]
OK: 27137 distinct packages available
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/community/armv7/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/main/armv7/APKINDEX.tar.gz
ERROR: unable to select packages:
  chromium (no such package):
    required by: world[chromium]
localhost:~#

**Comment by fahadali32** [comment]
> were you able to log in to alpine?

Yes

**Comment by fahadali32** [comment]
![Screenshot_2021-06-03-15-28-36-873_com termux](https://user-images.githubusercontent.com/38833848/120622175-65efbb80-c480-11eb-8500-22380651ff33.jpg)

**Comment by rishabhrpg** [comment]
@fahadali32 
Use these commands it will work.
proot-distro login alpine
apk update && apk add --no-cache nmap && \
  echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
  echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
  apk update && \
  apk add --no-cache \
  chromium
