### ISSUE TITLE
Unsupported platform: android

### ISSUE THREAD

**Issue by sintret** [rishabhrpg/puppeteer-on-termux#6]
Output:
/root/puppeteer-on-termux/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26
        throw new Error(message);
              ^

Error: Unsupported platform: android

**Comment by rishabhrpg** [comment]
You need to login to the Alpine distro first. Android binary are not natively supported by Termux.

**Comment by JS-junior** [comment]
It works! On my phone! Damn! Thank you so much!!
Can I do e2e testing with cypress and jest??

**Comment by rishabhrpg** [comment]
@JS-junior why not I just tested this with chromium 97 on Android 12 and it still works. however, some changes were needed I have pushed a commit for that.
